### ISSUE TITLE
Chao Monkey: Breaking Rides

### ISSUE THREAD

**Issue by davideverett89** [nss-evening-cohort-11/nutshell-jedis-stormtroopers#44]
## USER STORY
As a user, when the Chaos Monkey breaks a ride, the ride should no longer be operational.

## AC

WHEN a ride is broken
THEN a staff member can no longer be assigned to that ride
AND all current assignment to that ride should be deleted.

## DEV NOTES
- [x] Write a smash function that accepts an `assetId` as a parameter and finds all `jobTypes` associated with that `assetId`, and then finds all `assignments` that were associated with that `jobType`, and deletes those assignments.
- [x] Change case 3 of of `randomChaosMonkeyStrike` switch function to call this smash function.

**Comment by bwhitworth** [comment]
👍
