### ISSUE TITLE
Chaos Monkey History

### ISSUE THREAD

**Issue by davideverett89** [nss-evening-cohort-11/nutshell-jedis-stormtroopers#46]
## USER STORY
As a user, I want to be able to access a chaos monkey dashboard, that shows a complete history of the chaos monkey and is filterable by date, and has filters to show when chaos monkey kidnapped staff, broke equipment, or broke rides.

## AC
  
WHEN I see the chaos monkey dashboard,
THEN I can see a complete history of what the chaos monkey has done
AND I should be able to filter those events.

## DEV NOTES
- [x] Create another div on the main dashboard, this will contain the total history of all chaos monkey events.
- [x] Alter the chaos monkey function so that it creates an object and pushes that data to the chaos monkey collection in Firebase.
- [x] Get that data from firebase and print it to the new div as a list.
- [x] Make it look nice.
- [x] Make sure the events filter into their respective sections of the dashboard.

**Comment by bwhitworth** [comment]
Some of these bullets/sections needed to be done differently, due to restructuring our seed data/ ERDs yesterday.
