### ISSUE TITLE
Calendar View: Week

### ISSUE THREAD

**Issue by davideverett89** [nss-evening-cohort-11/nutshell-jedis-stormtroopers#51]
## USER STORY
As a user, I should be able to view the schedule in a calendar view for a typical week (monday - sunday)

## AC
WHEN I open the calendar dashboard
THEN I should a 7 day schedule
AND each day will be divided into AM and PM
AND show the details of that shift.

## DEV NOTES
- [ ] Create a div for the week.
- [ ] In this div, create seven more div for each day of the week, with id's of Monday - Sunday.
- [ ] Inside the div for each day, cards for either AM or PM will exist depending on if that shift has been assigned for that day.
- [ ] Create a function that will get all of the shifts for that day, create a card for each one that display the details of that shift: Staff name, department (vendors, equipment, dinos, etc), name of specific entity, and whether the shift is AM or PM.

**Comment by bwhitworth** [comment]
![image](https://user-images.githubusercontent.com/52139891/80439343-ef22df00-88cb-11ea-8b3a-0c15f14c957d.png)
