### ISSUE TITLE
Adding New Job when entity is created

### ISSUE THREAD

**Issue by davideverett89** [nss-evening-cohort-11/nutshell-jedis-stormtroopers#63]
## USER STORY
As a user, I should create an appropriate number of jobs each time a dino, ride, or vendor is added to the park.

## AC
WHEN the user adds a new dino, ride, or vendor
THEN an appropriate number of jobs should be created
AND those jobs should be seeded into the `jobs.json` collection

## DEV NOTES
- [x] new dinos need to add 28 jobs (2x am/pm x 7 days)
- [x] new rides need to add 14 jobs (am/pm x7 days)
- [x] new vendors need to add 14 jobs (am/pm x7 days)
- [x] add this feature to the function which creates each new entity, so that it adds these upon Submit

**Comment by bwhitworth** [comment]
PR #84
